"""
Narrator: builds a Showboat-style markdown document narrating the poster run.

Inspired by Simon Willison's Showboat (2026) -- the idea that an agent should
produce a human-readable artifact demonstrating exactly what happened during
execution, not just the final output.

The narrator accumulates sections as the system runs:
- Header with config and standards inventory
- One section per tick showing which nerd fired, why, and what it produced
- Inline data excerpts (SPARQL results, icon metadata, palette colors)
- Embedded poster image and provenance graph excerpt at the end

The result is a standalone markdown file that tells the story of one poster
generation: what happened, in what order, and why.
"""

from __future__ import annotations
from datetime import datetime
from pathlib import Path


class Narrator:
    """Accumulates a narrated markdown document of a NERDS run."""

    def __init__(self):
        self._sections: list[str] = []
        self._start_time = datetime.now()

    def header(self, seed: int | None, max_ticks: int, nerd_names: list[str]):
        """Write the document header."""
        ts = self._start_time.strftime("%Y-%m-%d %H:%M:%S")
        seed_str = str(seed) if seed is not None else "random"
        self._sections.append(f"""# Semantic NERDS: Poster Generation Narrative

*Generated {ts} &mdash; seed {seed_str}, max {max_ticks} ticks*

---

## Standards in play

| Standard | Role | Source |
|---|---|---|
| **RDF + JSON-LD** | Blackboard is an RDF graph; items are triples | W3C Rec 2014/2020 |
| **PROV-O** | Every item traces back to the nerd that made it | W3C Rec 2013 |
| **SKOS** | Item types are concepts in a navigable hierarchy | W3C Rec 2009 |
| **SHACL** | Nerd preconditions are declarative shapes | W3C Rec 2017 |
| **Schema.org** | Movie data uses `schema:Movie` vocabulary | Community std |
| **Dublin Core** | Metadata fields: `dcterms:creator`, `dcterms:type`, etc. | ISO 15836 |
| **Wikidata SPARQL** | Live movie data from the world's knowledge graph | CC0 |
| **Noun Project API** | Genre-relevant icons via OAuth1 | Commercial API |

## Nerds roster

{', '.join(f'**{n}**' for n in nerd_names)}

---

## The run

""")

    def tick_idle(self, tick: int):
        """Record an idle tick (no eligible nerd)."""
        self._sections.append(
            f"> **Tick {tick}** &mdash; no eligible nerd, idling\n\n")

    def tick_nerd(self, tick: int, nerd_name: str, items_produced: list[str],
                  detail: str = ""):
        """Record a nerd firing."""
        items_str = ", ".join(f"`{t}`" for t in items_produced) if items_produced else "*(nothing)*"
        section = f"### Tick {tick}: {nerd_name}\n\n"
        section += f"Produced: {items_str}\n\n"
        if detail:
            section += f"{detail}\n\n"
        self._sections.append(section)

    def note(self, text: str):
        """Add a freeform narrative note."""
        self._sections.append(f"{text}\n\n")

    def data_block(self, label: str, content: str, lang: str = ""):
        """Add a labeled code/data block."""
        self._sections.append(
            f"**{label}:**\n\n```{lang}\n{content}\n```\n\n")

    def completion(self, tick: int, item_count: int, triple_count: int):
        """Record completion."""
        self._sections.append(f"""---

## Completion

**Poster declared complete at tick {tick}.**

- {item_count} items on the blackboard
- {triple_count} RDF triples in the graph

""")

    def timeout(self, tick: int, max_ticks: int):
        """Record a timeout (max ticks reached)."""
        self._sections.append(f"""---

## Timeout

**Max ticks reached ({max_ticks}).** Rendering what we have after {tick} ticks.

""")

    def poster_image(self, image_path: str):
        """Embed the poster image."""
        self._sections.append(f"""## The poster

![Generated poster]({image_path})

""")

    def provenance_excerpt(self, turtle_excerpt: str):
        """Include a provenance graph excerpt."""
        self._sections.append(f"""## Provenance (excerpt)

The full provenance graph is exported as Turtle RDF. Here's a sample showing
how PROV-O traces items back through activities to their nerd agents:

```turtle
{turtle_excerpt}
```

""")

    def blackboard_summary(self, type_counts: dict[str, int]):
        """Add a final blackboard summary table."""
        rows = "\n".join(f"| {tag} | {count} |"
                         for tag, count in sorted(type_counts.items()))
        self._sections.append(f"""## Blackboard summary

| Artifact type | Count |
|---|---|
{rows}

""")

    def footer(self):
        """Write the document footer."""
        elapsed = datetime.now() - self._start_time
        self._sections.append(f"""---

*Total wall-clock time: {elapsed.total_seconds():.1f}s*

*Generated by Semantic NERDS (week 8) &mdash; a computational caricature
of a blackboard architecture, grounded in W3C semantic web standards.*

*No LLM was used at runtime. Every decision was made by a dumb specialist
reading RDF triples off a shared graph.*
""")

    def save(self, path: Path):
        """Write the accumulated narrative to a markdown file."""
        path.write_text("".join(self._sections))

    def text(self) -> str:
        """Return the accumulated narrative as a string."""
        return "".join(self._sections)
